on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: |
          curl -X POST "${VERCEL_DEPLOY_HOOKS_URL}"
        env:
          VERCEL_DEPLOY_HOOKS_URL: ${{ secrets.VERCEL_DEPLOY_HOOKS_URL }}
